name: Build image

on:    
  push:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          path: OpenROAD-flow-scripts
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build OpenROAD
        run: |
          cd OpenROAD-flow-scripts
          ./build_openroad.sh --os=ubuntu22.04
      - 
        name: Tag image
        run: docker tag openroad/flow-ubuntu22.04-builder killruana/openroad:latest
      - 
        name: Push image
        run: docker push killruana/openroad:latest
